#!/usr/bin/env sh

## Start the Gnome keyring daemon on boot to get GUI prompts
# see https://wiki.archlinux.org/title/GNOME/Keyring#Without_a_display_manager
dbus-update-activation-environment --all
eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK

# Set X11 error files to XDG-compliant folder
ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
